import { createContext, useContext, useEffect, useState, ReactNode, useCallback } from "react";
import api from "@/services/api";

export type Lang = "fr" | "en";

export const announcementTranslations: Record<string, string> = {
  "Réservé aux professionnels": "Reserved for professionals",
  "Prix HT — TVA 20%": "Prices excl. VAT — 20% VAT",
  "Franco de port dès 300€ HT": "Free shipping from €300 excl. VAT",
  "Fabrication française": "Made in France",
  "Tarifs dégressifs": "Volume discounts",
  "Livraison 48h": "48h delivery",
};

export interface LocaleInfo {
  code: string;
  name: string;
  native_name: string;
  flag_emoji: string;
  is_default: boolean;
  direction: string;
}

const dict = {
  fr: {
    "nav.home": "Accueil",
    "nav.new": "Nouveautés",
    "nav.necklaces": "Colliers",
    "nav.earrings": "Boucles",
    "nav.rings": "Bagues",
    "nav.bracelets": "Bracelets",
    "nav.atelier": "L'Atelier",
    "nav.proSpace": "Espace pro",
    "nav.account": "Mon compte",
    "nav.orders": "Mes commandes",
    "nav.logout": "Déconnexion",
    "nav.login": "Connexion pro",
    "nav.register": "Créer un compte pro",
    "common.search": "Recherche",
    "common.cart": "Panier",
    "common.menu": "Menu",
    "common.close": "Fermer",
    "common.addToCart": "Ajouter au panier",
    "common.seeAllCatalog": "Voir tout le catalogue →",
    "common.seeAll": "Voir tout →",
    "common.pieces": "pièces",
    "common.new": "Nouveauté",
    "common.ref": "Réf.",
    "common.min": "Min.",
    "common.recommendedPrice": "PVC conseillé",
    "common.stock": "Stock",
    "common.pcs": "pcs",
    "bestsellers.eyebrow": "Best-sellers",
    "bestsellers.heading": "Les pièces que vos clients",
    "bestsellers.headingEm": "adorent",
    "bestsellers.description": "Les références les plus commandées par notre réseau de revendeurs.",
    "categories.eyebrow": "Univers",
    "categories.heading": "Explorez nos",
    "categories.headingEm": "collections",
    "categories.description": "Chaque pièce est dessinée et fabriquée dans nos ateliers français.",
    "newArrivals.heading": "Les",
    "newArrivals.headingEm": "nouvelles pièces",
    "newArrivals.description": "Les 4 dernières références dans chacun de nos univers.",
    "footer.tagline": "Grossiste de bijoux faits main à Paris depuis 2016. Réservé aux professionnels.",
    "footer.copyright": "© 2026 MAISON LUNE · Grossiste B2B",
    "footer.catalog": "Catalogue",
    "footer.maison": "Maison",
    "footer.proInfo": "Infos pro",
    "footer.shipping": "Livraison & retours",
    "footer.atelierLink": "L'atelier",
    "footer.becomeReseller": "Devenir revendeur",
    "footer.contact": "Contact",
    "footer.faq": "FAQ",
    "footer.cgv": "CGV",
    "footer.legal": "Mentions légales",
    "footer.privacy": "Confidentialité",
    "footer.newsletterTitle": "Newsletter B2B",
    "footer.newsletterHeading": "Les nouveautés en avant-première",
    "footer.newsletterText": "Catalogues, fiches produit, offres revendeurs : tout directement dans votre boîte pro.",
    "footer.emailPlaceholder": "Votre email professionnel",
    "footer.subscribe": "S'inscrire",
    "search_placeholder": "Rechercher un nom, une référence, une description...",
    "all_universes": "Tous les univers",
    "sort_by_relevance": "Trier par : pertinence",
    "price_ascending": "Prix croissant",
    "price_descending": "Prix décroissant",
    "alpha_az": "Alphabétique A-Z",
    "alpha_za": "Alphabétique Z-A",
    "in_stock": "En stock",
    "all_tags": "Tous les tags",
    "all_materials": "Tous les matériaux",
    "all_finishes": "Toutes les finitions",
    "reset_filters": "Réinitialiser les filtres",
    "filter_by_letter": "Filtrer par lettre",
    "references_singular": "référence",
    "references_plural": "références",
    "recycled_gold": "Or recyclé",
    "lifetime_warranty": "Garantie",
    "made_in": "Made in",
    "cart.your_cart": "Votre panier",
    "cart.login_required": "Connexion requise",
    "cart.login_required_desc": "Connectez-vous pour valider votre commande.",
    "cart.account_pending": "Compte en attente de validation",
    "cart.account_pending_desc": "Votre compte pro doit être validé par notre équipe avant toute commande.",
    "cart.discover_catalog": "Découvrir le catalogue",
    "cart.remove": "Retirer",
    "cart.clear_cart": "Vider le panier",
    "cart.summary": "Récapitulatif",
    "cart.subtotal_ht": "Sous-total HT",
    "cart.vat": "TVA (20%)",
    "cart.shipping": "Livraison",
    "cart.free": "Offerte",
    "cart.total_ttc": "Total TTC",
    "cart.proceed_order": "Procéder à la commande",
    "cart.free_shipping_from": "Livraison offerte dès",
    "cart.payment_terms": "Paiement à 30 jours après validation.",
    "cart.added": "Ajouté au panier",
    "cart.proceed_payment": "Procéder au paiement",
    "product.login_required": "Connexion requise",
    "product.login_required_desc": "Connectez-vous à votre compte pro pour commander.",
    "product.variations_required": "Variations requises",
    "product.variations_required_desc": "Veuillez choisir une option pour chaque variation.",
    "product.insufficient_qty": "Quantité insuffisante",
    "product.insufficient_qty_desc": "Minimum {moq} pièces.",
    "product.material": "Matière",
    "product.finish": "Finition",
    "product.quality": "Qualité",
    "product.min_qty": "Quantité minimale",
    "product.packaging": "Conditionnement",
    "product.by": "Par",
    "product.sold_out": "Épuisé",
    "product.choose_variations": "Choisir les variations",
    "product.decrease": "Diminuer",
    "product.increase": "Augmenter",
    "product.login_link": "Connectez-vous",
    "product.login_desc": "à votre compte professionnel pour commander.",
    "product.delivery_48h": "Livraison 48h",
    "product.lifetime_warranty": "Garantie à vie",
    "product.made_in_france": "Fabrication française",
    "product.you_will_also_like": "Vous aimerez aussi",
    "product.ht_per_piece": "HT / pièce",
    "product.recommended_price": "Prix public conseillé",
    "checkout.title": "Finaliser la commande",
    "checkout.checkout": "Checkout",
    "checkout.account_must_be_approved": "Votre compte pro doit être validé avant de pouvoir commander.",
    "checkout.back_to_account": "Retour à mon compte",
    "checkout.view_catalog": "Voir le catalogue",
    "checkout.terms_required": "Conditions générales",
    "checkout.terms_required_desc": "Vous devez accepter les CGV pour continuer.",
    "checkout.finalize": "Finaliser la commande",
    "checkout.finalize_subtitle": "Vérifiez vos informations avant le paiement",
    "checkout.address_step": "Adresse",
    "checkout.review_step": "Récapitulatif",
    "checkout.shipping_address": "Adresse de livraison",
    "checkout.continue": "Continuer",
    "checkout.edit": "Modifier",
    "checkout.carrier": "Transporteur",
    "checkout.notes": "Notes / Instructions",
    "checkout.notes_placeholder": "Instructions de livraison, code d'accès, etc. (optionnel)",
    "checkout.accept_terms_prefix": "J'accepte les",
    "checkout.terms_link": "conditions générales de vente",
    "checkout.accept_terms_suffix": "et je reconnais avoir pris connaissance des modalités de paiement et de livraison.",
    "checkout.proceed_payment": "Procéder au paiement",
    "payment.title": "Paiement",
    "payment.payment": "Paiement",
    "payment.login_to_see_status": "Connectez-vous pour voir le statut de votre paiement.",
    "payment.sign_in": "Se connecter",
    "payment.success_title": "Paiement réussi",
    "payment.confirmation": "Confirmation",
    "payment.thank_you": "Merci pour votre commande !",
    "payment.success_desc": "Votre paiement a été traité avec succès.",
    "payment.loading_order": "Chargement des détails de la commande…",
    "payment.payment_confirmed_desc": "Votre paiement a été confirmé. Vous pouvez consulter vos commandes dans votre espace.",
    "payment.failed_title": "Paiement échoué",
    "payment.failure": "Échec",
    "payment.failed_heading": "Paiement non abouti",
    "payment.error_default": "Une erreur est survenue lors du traitement de votre paiement.",
    "payment.what_happened": "Que s'est-il passé ?",
    "payment.card_refused": "Votre carte a peut-être été refusée par votre banque",
    "payment.incorrect_info": "Les informations de paiement étaient incorrectes",
    "payment.technical_error": "Une erreur technique est survenue pendant le traitement",
    "payment.what_to_do": "Que faire ?",
    "payment.check_card_info": "Vérifiez les informations de votre carte bancaire",
    "payment.contact_bank": "Contactez votre banque pour autoriser le paiement",
    "payment.try_other_card": "Essayez avec une autre carte bancaire",
    "payment.back_to_cart": "Retour au panier",
    "payment.retry_payment": "Réessayer le paiement",
    "payment.need_help": "Besoin d'aide ?",
    "payment.contact_us": "Contactez-nous",
    "payment.secure_payment": "Paiement sécurisé",
    "payment.secure_payment_subtitle": "Finalisez votre commande en toute sécurité",
    "payment.shipping_info": "Informations de livraison",
    "payment.initializing": "Initialisation du paiement…",
    "payment.back_to_checkout": "Retour au checkout",
    "payment.no_items": "Aucun article à payer.",
    "payment.your_order": "Votre commande",
    "payment.order_label": "Commande",
    "payment.total_to_pay": "Total à payer",
    "payment.processing": "Traitement en cours…",
    "payment.pay": "Payer",
    "payment.secured_by_stripe": "Paiement sécurisé par Stripe · Vos données sont protégées",
    "payment.error_occurred": "Une erreur est survenue lors du paiement.",
    "payment.init_error": "Impossible d'initialiser le paiement.",
    "order.pending": "En attente",
    "order.confirmed": "Confirmée",
    "order.preparing": "En préparation",
    "order.shipped": "Expédiée",
    "order.delivered": "Livrée",
    "order.cancelled": "Annulée",
    "order.reference": "Référence",
    "order.status": "Statut",
    "order.items_ordered": "Articles commandés",
    "order.view_orders": "Voir mes commandes",
    "order.pdf_invoice": "Facture PDF",
    "common.loading": "Chargement…",
    "pro.dashboard": "Tableau de bord",
    "pro.home": "Accueil",
    "pro.orders": "Commandes",
    "pro.support": "Support",
    "pro.catalog": "Catalogue",
    "pro.profile": "Profil",
    "pro.navigation": "Navigation",
    "pro.need_help": "Besoin d'aide ?",
    "pro.team_available": "Notre équipe est disponible du lundi au vendredi.",
    "pro.contact_support": "Contacter le support",
    "account.pro_space": "Espace pro",
    "account.edit_profile": "Modifier mon profil",
    "account.account_info": "Informations du compte",
    "account.personal_info": "Informations personnelles",
    "account.name": "Nom",
    "account.contact_name": "Nom du contact",
    "account.phone": "Téléphone",
    "account.company": "Entreprise",
    "account.company_name": "Raison sociale",
    "account.vat_number": "N° TVA intracommunautaire",
    "account.address": "Adresse",
    "account.city": "Ville",
    "account.postal_code": "Code postal",
    "account.country": "Pays",
    "account.saving": "Enregistrement...",
    "account.save": "Enregistrer",
    "account.cancel": "Annuler",
    "account.hello": "Bonjour",
    "account.account_approved": "Compte validé",
    "account.account_approved_desc": "Votre compte est actif. Vous pouvez passer des commandes.",
    "account.account_pending": "Compte en attente de validation",
    "account.account_pending_desc": "Votre compte sera validé par un administrateur sous 24-48h.",
    "account.total_orders": "Total commandes",
    "account.since_registration": "Depuis l'inscription",
    "account.in_progress": "En cours",
    "account.pending_or_confirmed": "En attente ou confirmée",
    "account.shipped": "Expédiées",
    "account.in_delivery": "En livraison",
    "account.total_spent": "Total dépensé",
    "account.all_taxes_included": "Toutes taxes comprises",
    "account.quick_actions": "Actions rapides",
    "account.order": "Commander",
    "account.access_catalog": "Accéder au catalogue",
    "account.view_history": "Voir l'historique",
    "account.ticket_open": "ticket(s) ouvert(s)",
    "account.no_ticket": "Aucun ticket",
    "account.edit_info": "Modifier les infos",
    "account.recent_orders": "Commandes récentes",
    "account.view_all": "Voir tout",
    "account.no_orders_yet": "Vous n'avez pas encore passé de commande.",
    "account.view_catalog": "Voir le catalogue",
    "account.open_tickets": "Tickets ouverts",
    "account.company_info": "Informations entreprise",
    "account.edit": "Modifier",
    "account.logged_in_as": "Connecté en tant que",
    "account.logout": "Se déconnecter",
    "account.profile_updated": "Profil mis à jour",
    "account.profile_updated_desc": "Vos informations ont été enregistrées.",
    "account.save_error": "Impossible de sauvegarder les modifications.",
    "account.invoice_error": "Impossible de télécharger la facture.",
    "ticket.open": "Ouvert",
    "ticket.pending": "En attente",
    "common.error": "Erreur",
    "shop.catalog_b2b": "Catalogue B2B",
    "shop.full_catalog": "Le catalogue complet",
    "shop.catalog_subtitle": "Toutes les références Maison Lune disponibles pour les revendeurs professionnels.",
    "shop.shop": "Boutique",
    "shop.no_results": "Aucun résultat pour votre recherche.",
    "orders.my_orders": "Mes commandes",
    "orders.orders_subtitle": "Historique complet de vos commandes et suivi en temps réel",
    "orders.total": "Total",
    "orders.in_progress": "En cours",
    "orders.search_placeholder": "Rechercher par référence ou produit...",
    "orders.all_statuses": "Tous les statuts",
    "orders.all_dates": "Toutes les dates",
    "orders.last_7_days": "7 derniers jours",
    "orders.last_30_days": "30 derniers jours",
    "orders.last_90_days": "90 derniers jours",
    "orders.orders_found_singular": "commande trouvée",
    "orders.orders_found_plural": "commandes trouvées",
    "orders.no_orders_found": "Aucune commande trouvée.",
    "orders.date": "Date",
    "orders.items": "Articles",
    "orders.actions": "Actions",
    "orders.article": "article",
    "orders.articles": "articles",
    "orders.view_details": "Voir les détails",
    "orders.open_ticket": "Ouvrir un ticket",
    "orders.cancel": "Annuler",
    "orders.details": "Détails",
    "orders.invoice": "Facture",
    "orders.load_error": "Impossible de charger vos commandes.",
    "orders.cancel_confirm": "Annuler la commande {ref} ?",
    "orders.order_cancelled": "Commande annulée",
    "orders.order_cancelled_desc": "La référence {ref} a été annulée.",
    "orders.cancel_error": "Impossible d'annuler cette commande.",
    "contact.message_sent": "Message envoyé",
    "contact.message_sent_desc": "Notre équipe vous répond sous 24h ouvrées.",
    "contact.write_to_us": "Nous écrire",
    "contact.sales_contact": "Contact commercial",
    "contact.contact_subtitle": "Une question sur un produit, un devis, ou une demande de partenariat ?",
    "contact.contact": "Contact",
    "contact.name": "Nom",
    "contact.company": "Société",
    "contact.professional_email": "Email professionnel",
    "contact.your_message": "Votre message",
    "contact.send": "Envoyer",
    "contact.phone": "Téléphone",
    "contact.workshop": "Atelier",
    "contact.showroom_title": "Showroom sur rendez-vous",
    "contact.showroom_text": "Du lundi au vendredi, 10h–18h. Prenez contact pour venir découvrir les collections en avant-première.",
    "login.login_failed": "Connexion impossible",
    "login.welcome_back": "Bon retour !",
    "login.logged_in": "Vous êtes connecté.",
    "login.reseller_login": "Connexion revendeur",
    "login.login_subtitle": "Accédez à votre catalogue, vos tarifs HT et votre historique de commandes.",
    "login.login": "Connexion",
    "login.password": "Mot de passe",
    "login.logging_in": "Connexion...",
    "login.sign_in": "Se connecter",
    "login.no_account": "Pas encore de compte ?",
    "login.open_pro_account": "Ouvrir un compte pro",
    "register.register_failed": "Inscription impossible",
    "register.account_created": "Compte créé",
    "register.account_created_desc": "Votre compte est en attente de validation par notre équipe (24-48h).",
    "register.become_reseller": "Devenir revendeur",
    "register.open_pro_account": "Ouvrir un compte pro",
    "register.register_subtitle": "Réservé aux professionnels titulaires d'un numéro SIRET valide. Validation sous 24-48h.",
    "register.register": "Inscription",
    "register.siret_label": "Numéro SIRET (14 chiffres)",
    "register.password_label": "Mot de passe (min. 8 caractères)",
    "register.creating": "Création...",
    "register.create_account": "Créer mon compte pro",
    "register.already_client": "Déjà client ?",
    "orderdetail.order": "Commande",
    "orderdetail.load_error": "Impossible de charger les détails de la commande.",
    "orderdetail.order_not_found": "Commande introuvable",
    "orderdetail.order_not_found_desc": "Cette commande n'existe pas ou n'est pas accessible.",
    "orderdetail.back_to_orders": "Retour aux commandes",
    "orderdetail.tracking_number": "N° de suivi",
    "orderdetail.track_package": "Suivre mon colis",
    "orderdetail.cancel_order": "Annuler la commande",
  },
  en: {
    "nav.home": "Home",
    "nav.new": "New",
    "nav.necklaces": "Necklaces",
    "nav.earrings": "Earrings",
    "nav.rings": "Rings",
    "nav.bracelets": "Bracelets",
    "nav.atelier": "Atelier",
    "nav.proSpace": "Pro space",
    "nav.account": "My account",
    "nav.orders": "My orders",
    "nav.logout": "Sign out",
    "nav.login": "Pro sign in",
    "nav.register": "Create a pro account",
    "common.search": "Search",
    "common.cart": "Cart",
    "common.menu": "Menu",
    "common.close": "Close",
    "common.addToCart": "Add to cart",
    "common.seeAllCatalog": "View full catalog →",
    "common.seeAll": "View all →",
    "common.pieces": "pieces",
    "common.new": "New",
    "common.ref": "Ref.",
    "common.min": "Min.",
    "common.recommendedPrice": "RRP",
    "common.stock": "Stock",
    "common.pcs": "pcs",
    "bestsellers.eyebrow": "Best-sellers",
    "bestsellers.heading": "The pieces your customers",
    "bestsellers.headingEm": "love",
    "bestsellers.description": "The most ordered references by our reseller network.",
    "categories.eyebrow": "Universes",
    "categories.heading": "Explore our",
    "categories.headingEm": "collections",
    "categories.description": "Each piece is designed and made in our French workshops.",
    "newArrivals.heading": "The",
    "newArrivals.headingEm": "new pieces",
    "newArrivals.description": "The 4 latest references in each of our universes.",
    "footer.tagline": "Handmade jewelry wholesaler from Paris since 2016. Reserved for professionals.",
    "footer.copyright": "© 2026 MAISON LUNE · B2B Wholesaler",
    "footer.catalog": "Catalog",
    "footer.maison": "Maison",
    "footer.proInfo": "Pro info",
    "footer.shipping": "Shipping & returns",
    "footer.atelierLink": "The atelier",
    "footer.becomeReseller": "Become a reseller",
    "footer.contact": "Contact",
    "footer.faq": "FAQ",
    "footer.cgv": "Terms",
    "footer.legal": "Legal notice",
    "footer.privacy": "Privacy",
    "footer.newsletterTitle": "B2B Newsletter",
    "footer.newsletterHeading": "New arrivals in preview",
    "footer.newsletterText": "Catalogs, product sheets, reseller offers: directly in your pro inbox.",
    "footer.emailPlaceholder": "Your professional email",
    "footer.subscribe": "Subscribe",
    "search_placeholder": "Search by name, reference, description...",
    "all_universes": "All universes",
    "sort_by_relevance": "Sort by: relevance",
    "price_ascending": "Price: low to high",
    "price_descending": "Price: high to low",
    "alpha_az": "Alphabetical A-Z",
    "alpha_za": "Alphabetical Z-A",
    "in_stock": "In stock",
    "all_tags": "All tags",
    "all_materials": "All materials",
    "all_finishes": "All finishes",
    "reset_filters": "Reset filters",
    "filter_by_letter": "Filter by letter",
    "references_singular": "reference",
    "references_plural": "references",
    "recycled_gold": "Recycled gold",
    "lifetime_warranty": "Warranty",
    "made_in": "Made in",
    "cart.your_cart": "Your Cart",
    "cart.login_required": "Login Required",
    "cart.login_required_desc": "Please sign in to complete your order.",
    "cart.account_pending": "Account Pending Approval",
    "cart.account_pending_desc": "Your pro account must be approved by our team before ordering.",
    "cart.discover_catalog": "Discover the Catalog",
    "cart.remove": "Remove",
    "cart.clear_cart": "Clear Cart",
    "cart.summary": "Summary",
    "cart.subtotal_ht": "Subtotal excl. VAT",
    "cart.vat": "VAT (20%)",
    "cart.shipping": "Shipping",
    "cart.free": "Free",
    "cart.total_ttc": "Total incl. VAT",
    "cart.proceed_order": "Proceed to Order",
    "cart.free_shipping_from": "Free shipping from",
    "cart.payment_terms": "Payment 30 days after approval.",
    "cart.added": "Added to cart",
    "cart.proceed_payment": "Proceed to Payment",
    "product.login_required": "Login Required",
    "product.login_required_desc": "Sign in to your pro account to order.",
    "product.variations_required": "Variations Required",
    "product.variations_required_desc": "Please choose an option for each variation.",
    "product.insufficient_qty": "Insufficient Quantity",
    "product.insufficient_qty_desc": "Minimum {moq} pieces.",
    "product.material": "Material",
    "product.finish": "Finish",
    "product.quality": "Quality",
    "product.min_qty": "Minimum Quantity",
    "product.packaging": "Packaging",
    "product.by": "By",
    "product.sold_out": "Sold Out",
    "product.choose_variations": "Choose Variations",
    "product.decrease": "Decrease",
    "product.increase": "Increase",
    "product.login_link": "Sign in",
    "product.login_desc": "to your professional account to order.",
    "product.delivery_48h": "48h Delivery",
    "product.lifetime_warranty": "Lifetime Warranty",
    "product.made_in_france": "Made in France",
    "product.you_will_also_like": "You Will Also Like",
    "product.ht_per_piece": "excl. VAT / piece",
    "product.recommended_price": "Recommended retail price",
    "checkout.title": "Checkout",
    "checkout.checkout": "Checkout",
    "checkout.account_must_be_approved": "Your pro account must be approved before ordering.",
    "checkout.back_to_account": "Back to my account",
    "checkout.view_catalog": "View catalog",
    "checkout.terms_required": "Terms & Conditions",
    "checkout.terms_required_desc": "You must accept the T&Cs to continue.",
    "checkout.finalize": "Complete Your Order",
    "checkout.finalize_subtitle": "Review your information before payment",
    "checkout.address_step": "Address",
    "checkout.review_step": "Review",
    "checkout.shipping_address": "Shipping Address",
    "checkout.continue": "Continue",
    "checkout.edit": "Edit",
    "checkout.carrier": "Carrier",
    "checkout.notes": "Notes / Instructions",
    "checkout.notes_placeholder": "Delivery instructions, access code, etc. (optional)",
    "checkout.accept_terms_prefix": "I accept the",
    "checkout.terms_link": "terms and conditions",
    "checkout.accept_terms_suffix": "and acknowledge that I have read the payment and delivery terms.",
    "checkout.proceed_payment": "Proceed to Payment",
    "payment.title": "Payment",
    "payment.payment": "Payment",
    "payment.login_to_see_status": "Sign in to view your payment status.",
    "payment.sign_in": "Sign In",
    "payment.success_title": "Payment Successful",
    "payment.confirmation": "Confirmation",
    "payment.thank_you": "Thank you for your order!",
    "payment.success_desc": "Your payment has been processed successfully.",
    "payment.loading_order": "Loading order details…",
    "payment.payment_confirmed_desc": "Your payment has been confirmed. You can view your orders in your account.",
    "payment.failed_title": "Payment Failed",
    "payment.failure": "Failure",
    "payment.failed_heading": "Payment Not Completed",
    "payment.error_default": "An error occurred while processing your payment.",
    "payment.what_happened": "What happened?",
    "payment.card_refused": "Your card may have been declined by your bank",
    "payment.incorrect_info": "The payment information was incorrect",
    "payment.technical_error": "A technical error occurred during processing",
    "payment.what_to_do": "What to do?",
    "payment.check_card_info": "Check your card information",
    "payment.contact_bank": "Contact your bank to authorize the payment",
    "payment.try_other_card": "Try with another card",
    "payment.back_to_cart": "Back to Cart",
    "payment.retry_payment": "Retry Payment",
    "payment.need_help": "Need help?",
    "payment.contact_us": "Contact us",
    "payment.secure_payment": "Secure Payment",
    "payment.secure_payment_subtitle": "Complete your order securely",
    "payment.shipping_info": "Shipping Information",
    "payment.initializing": "Initializing payment…",
    "payment.back_to_checkout": "Back to Checkout",
    "payment.no_items": "No items to pay for.",
    "payment.your_order": "Your Order",
    "payment.order_label": "Order",
    "payment.total_to_pay": "Total to pay",
    "payment.processing": "Processing…",
    "payment.pay": "Pay",
    "payment.secured_by_stripe": "Secured by Stripe · Your data is protected",
    "payment.error_occurred": "An error occurred during payment.",
    "payment.init_error": "Unable to initialize payment.",
    "order.pending": "Pending",
    "order.confirmed": "Confirmed",
    "order.preparing": "Preparing",
    "order.shipped": "Shipped",
    "order.delivered": "Delivered",
    "order.cancelled": "Cancelled",
    "order.reference": "Reference",
    "order.status": "Status",
    "order.items_ordered": "Items Ordered",
    "order.view_orders": "View My Orders",
    "order.pdf_invoice": "PDF Invoice",
    "common.loading": "Loading…",
    "pro.dashboard": "Dashboard",
    "pro.home": "Home",
    "pro.orders": "Orders",
    "pro.support": "Support",
    "pro.catalog": "Catalog",
    "pro.profile": "Profile",
    "pro.navigation": "Navigation",
    "pro.need_help": "Need help?",
    "pro.team_available": "Our team is available Monday to Friday.",
    "pro.contact_support": "Contact Support",
    "account.pro_space": "Pro Space",
    "account.edit_profile": "Edit My Profile",
    "account.account_info": "Account Information",
    "account.personal_info": "Personal Information",
    "account.name": "Name",
    "account.contact_name": "Contact Name",
    "account.phone": "Phone",
    "account.company": "Company",
    "account.company_name": "Company Name",
    "account.vat_number": "VAT Number",
    "account.address": "Address",
    "account.city": "City",
    "account.postal_code": "Postal Code",
    "account.country": "Country",
    "account.saving": "Saving...",
    "account.save": "Save",
    "account.cancel": "Cancel",
    "account.hello": "Hello",
    "account.account_approved": "Account Approved",
    "account.account_approved_desc": "Your account is active. You can place orders.",
    "account.account_pending": "Account Pending Approval",
    "account.account_pending_desc": "Your account will be approved by an administrator within 24-48h.",
    "account.total_orders": "Total Orders",
    "account.since_registration": "Since registration",
    "account.in_progress": "In Progress",
    "account.pending_or_confirmed": "Pending or confirmed",
    "account.shipped": "Shipped",
    "account.in_delivery": "In delivery",
    "account.total_spent": "Total Spent",
    "account.all_taxes_included": "All taxes included",
    "account.quick_actions": "Quick Actions",
    "account.order": "Order",
    "account.access_catalog": "Access catalog",
    "account.view_history": "View history",
    "account.ticket_open": "open ticket(s)",
    "account.no_ticket": "No tickets",
    "account.edit_info": "Edit info",
    "account.recent_orders": "Recent Orders",
    "account.view_all": "View all",
    "account.no_orders_yet": "You haven't placed any orders yet.",
    "account.view_catalog": "View catalog",
    "account.open_tickets": "Open Tickets",
    "account.company_info": "Company Information",
    "account.edit": "Edit",
    "account.logged_in_as": "Logged in as",
    "account.logout": "Sign Out",
    "account.profile_updated": "Profile Updated",
    "account.profile_updated_desc": "Your information has been saved.",
    "account.save_error": "Unable to save changes.",
    "account.invoice_error": "Unable to download invoice.",
    "ticket.open": "Open",
    "ticket.pending": "Pending",
    "common.error": "Error",
    "shop.catalog_b2b": "B2B Catalog",
    "shop.full_catalog": "Full Catalog",
    "shop.catalog_subtitle": "All Maison Lune references available for professional resellers.",
    "shop.shop": "Shop",
    "shop.no_results": "No results for your search.",
    "orders.my_orders": "My Orders",
    "orders.orders_subtitle": "Complete order history and real-time tracking",
    "orders.total": "Total",
    "orders.in_progress": "In Progress",
    "orders.search_placeholder": "Search by reference or product...",
    "orders.all_statuses": "All statuses",
    "orders.all_dates": "All dates",
    "orders.last_7_days": "Last 7 days",
    "orders.last_30_days": "Last 30 days",
    "orders.last_90_days": "Last 90 days",
    "orders.orders_found_singular": "order found",
    "orders.orders_found_plural": "orders found",
    "orders.no_orders_found": "No orders found.",
    "orders.date": "Date",
    "orders.items": "Items",
    "orders.actions": "Actions",
    "orders.article": "item",
    "orders.articles": "items",
    "orders.view_details": "View details",
    "orders.open_ticket": "Open a ticket",
    "orders.cancel": "Cancel",
    "orders.details": "Details",
    "orders.invoice": "Invoice",
    "orders.load_error": "Unable to load your orders.",
    "orders.cancel_confirm": "Cancel order {ref}?",
    "orders.order_cancelled": "Order Cancelled",
    "orders.order_cancelled_desc": "Reference {ref} has been cancelled.",
    "orders.cancel_error": "Unable to cancel this order.",
    "contact.message_sent": "Message Sent",
    "contact.message_sent_desc": "Our team will respond within 24 business hours.",
    "contact.write_to_us": "Write to Us",
    "contact.sales_contact": "Sales Contact",
    "contact.contact_subtitle": "A question about a product, a quote, or a partnership request?",
    "contact.contact": "Contact",
    "contact.name": "Name",
    "contact.company": "Company",
    "contact.professional_email": "Professional email",
    "contact.your_message": "Your message",
    "contact.send": "Send",
    "contact.phone": "Phone",
    "contact.workshop": "Workshop",
    "contact.showroom_title": "Showroom by Appointment",
    "contact.showroom_text": "Monday to Friday, 10am–6pm. Get in touch to discover our collections in preview.",
    "login.login_failed": "Login Failed",
    "login.welcome_back": "Welcome back!",
    "login.logged_in": "You are now logged in.",
    "login.reseller_login": "Reseller Sign In",
    "login.login_subtitle": "Access your catalog, wholesale prices, and order history.",
    "login.login": "Sign In",
    "login.password": "Password",
    "login.logging_in": "Signing in...",
    "login.sign_in": "Sign In",
    "login.no_account": "No account yet?",
    "login.open_pro_account": "Open a pro account",
    "register.register_failed": "Registration Failed",
    "register.account_created": "Account Created",
    "register.account_created_desc": "Your account is pending approval by our team (24-48h).",
    "register.become_reseller": "Become a Reseller",
    "register.open_pro_account": "Open a Pro Account",
    "register.register_subtitle": "Reserved for professionals with a valid SIRET number. Approval within 24-48h.",
    "register.register": "Register",
    "register.siret_label": "SIRET Number (14 digits)",
    "register.password_label": "Password (min. 8 characters)",
    "register.creating": "Creating...",
    "register.create_account": "Create my pro account",
    "register.already_client": "Already a client?",
    "orderdetail.order": "Order",
    "orderdetail.load_error": "Unable to load order details.",
    "orderdetail.order_not_found": "Order Not Found",
    "orderdetail.order_not_found_desc": "This order does not exist or is not accessible.",
    "orderdetail.back_to_orders": "Back to Orders",
    "orderdetail.tracking_number": "Tracking Number",
    "orderdetail.track_package": "Track My Package",
    "orderdetail.cancel_order": "Cancel Order",
  },
} as const;

type Key = keyof (typeof dict)["fr"];

interface Ctx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (k: Key) => string;
  locales: LocaleInfo[];
  isLoading: boolean;
}

const LanguageCtx = createContext<Ctx | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = typeof window !== "undefined" ? (localStorage.getItem("lang") as Lang | null) : null;
    return saved === "en" || saved === "fr" ? saved : "fr";
  });
  const [locales, setLocales] = useState<LocaleInfo[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    localStorage.setItem("lang", lang);
    localStorage.setItem("locale", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  useEffect(() => {
    const fetchLocales = async () => {
      try {
        const { data } = await api.get("/translations/locales");
        setLocales(data.locales || []);
      } catch {
        setLocales([
          { code: "fr", name: "French", native_name: "Français", flag_emoji: "🇫🇷", is_default: true, direction: "ltr" },
          { code: "en", name: "English", native_name: "English", flag_emoji: "🇬🇧", is_default: false, direction: "ltr" },
        ]);
      } finally {
        setIsLoading(false);
      }
    };

    fetchLocales();
  }, []);

  const setLang = useCallback((l: Lang) => {
    setLangState(l);

    api.post("/translations/set-locale", { locale: l }).catch(() => {
      console.warn("Failed to set locale on server");
    });

    window.location.reload();
  }, []);

  const t = useCallback((k: Key) => (dict[lang] as any)[k] ?? (dict.fr as any)[k] ?? k, [lang]);

  return (
    <LanguageCtx.Provider value={{ lang, setLang, t, locales, isLoading }}>
      {children}
    </LanguageCtx.Provider>
  );
};

export const useLang = () => {
  const c = useContext(LanguageCtx);
  if (!c) throw new Error("useLang must be used inside LanguageProvider");
  return c;
};
